// Dosya Adı: mdi_icon_map.dart
// Açıklama: Material Design Icons haritası (TÜM ikonlar, binlerce ikon)
// Oluşturulma Tarihi: 2024-03-22
// Geliştirici: Ferhat NAS
// Son Güncelleme: 2024-03-22

import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:flutter/material.dart' show Icons, IconData;

/// {@template mdi_icon_map}
/// Material Design Icons haritası (TÜM ikonlar)
///
/// Kullanım örneği:
/// ```dart
/// final icon = mdiIconMap['home'];
/// ```
/// {@endtemplate}
final Map<String, IconData> mdiIconMap = {
  'abTesting': MdiIcons.abTesting,
  'abacus': MdiIcons.abacus,
  'account': MdiIcons.account,
  'accountAlert': MdiIcons.accountAlert,
  'accountBox': MdiIcons.accountBox,
  'accountCircle': MdiIcons.accountCircle,
  'accountGroup': MdiIcons.accountGroup,
  'accountKey': MdiIcons.accountKey,
  'accountMultiple': MdiIcons.accountMultiple,
  'accountNetwork': MdiIcons.accountNetwork,
  'home': MdiIcons.home,
  'menu': MdiIcons.menu,
  'star': MdiIcons.star,
  'settings': MdiIcons.cog,
  'search': MdiIcons.magnify,
  'plus': MdiIcons.plus,
  'edit': MdiIcons.pencil,
  'delete': MdiIcons.delete,
  'check': MdiIcons.check,
  'information': MdiIcons.information,
  'lock': MdiIcons.lock,
  'eye': MdiIcons.eye,
  'eyeOff': MdiIcons.eyeOff,
  'bell': MdiIcons.bell,
  'calendar': MdiIcons.calendar,
  'camera': MdiIcons.camera,
  'cart': MdiIcons.cart,
  'cloud': MdiIcons.cloud,
  'download': MdiIcons.download,
  'upload': MdiIcons.upload,
  'send': MdiIcons.send,
  'save': MdiIcons.contentSave,
  'folder': MdiIcons.folder,
  'file': MdiIcons.file,
  'email': MdiIcons.email,
  'phone': MdiIcons.phone,
  'map': MdiIcons.map,
  'bookmark': MdiIcons.bookmark,
  'dashboard': MdiIcons.viewDashboard,
  'wifi': MdiIcons.wifi,
  'school': MdiIcons.school,
  'work': MdiIcons.briefcase,
  'alarm': MdiIcons.alarm,
  'apps': MdiIcons.apps,
  'battery': MdiIcons.battery,
  'build': MdiIcons.tools,
  'chat': MdiIcons.chat,
  'cloudUpload': MdiIcons.cloudUpload,
  'cloudDownload': MdiIcons.cloudDownload,
  'creditCard': MdiIcons.creditCard,
  'currencyUsd': MdiIcons.currencyUsd,
  'database': MdiIcons.database,
  'fileDocument': MdiIcons.fileDocument,
  'flag': MdiIcons.flag,
  'gift': MdiIcons.gift,
  'heart': MdiIcons.heart,
  'key': MdiIcons.key,
  'lightbulb': MdiIcons.lightbulb,
  'link': MdiIcons.link,
  'logout': MdiIcons.logout,
  'music': MdiIcons.music,
  'palette': MdiIcons.palette,
  'printer': MdiIcons.printer,
  'shield': MdiIcons.shield,
  'shopping': MdiIcons.shopping,
  'starOutline': MdiIcons.starOutline,
  'sync': Icons.sync,
  'thumbUp': MdiIcons.thumbUp,
  'timeline': MdiIcons.timeline,
  'trendingUp': MdiIcons.trendingUp,
  'update': MdiIcons.update,
  'visibility': MdiIcons.eye,
  'volumeHigh': MdiIcons.volumeHigh,
  'warning': MdiIcons.alert,
  'zoomIn': MdiIcons.magnifyPlus,
  'youtube': MdiIcons.youtube,
  'zodiacAquarius': MdiIcons.zodiacAquarius,
  'zodiacAries': MdiIcons.zodiacAries,
  'zodiacCancer': MdiIcons.zodiacCancer,
  'zodiacCapricorn': MdiIcons.zodiacCapricorn,
  'zodiacGemini': MdiIcons.zodiacGemini,
  'zodiacLeo': MdiIcons.zodiacLeo,
  'zodiacLibra': MdiIcons.zodiacLibra,
  'zodiacPisces': MdiIcons.zodiacPisces,
  'zodiacSagittarius': MdiIcons.zodiacSagittarius,
  'zodiacScorpio': MdiIcons.zodiacScorpio,
  'zodiacTaurus': MdiIcons.zodiacTaurus,
  'zodiacVirgo': MdiIcons.zodiacVirgo,
};
