// Dosya Adı: mdi_icon_map.dart
// Açıklama: Menü ikon seçimi için Material Icons haritası
// Oluşturulma Tarihi: 2024-03-22
// Geliştirici: Ferhat NAS
// Son Güncelleme: 2026-07-25

import 'package:flutter/material.dart' show Icons, IconData;

/// {@template mdi_icon_map}
/// Menü yönetimi ikon haritası (Material Icons).
///
/// Kullanım örneği:
/// ```dart
/// final icon = mdiIconMap['home'] ?? Icons.menu;
/// ```
/// {@endtemplate}
final Map<String, IconData> mdiIconMap = {
  'abTesting': Icons.science,
  'abacus': Icons.calculate,
  'account': Icons.person,
  'accountAlert': Icons.person_off,
  'accountBox': Icons.account_box,
  'accountCircle': Icons.account_circle,
  'accountGroup': Icons.groups,
  'accountKey': Icons.vpn_key,
  'accountMultiple': Icons.people,
  'accountNetwork': Icons.people_outline,
  'home': Icons.home,
  'menu': Icons.menu,
  'star': Icons.star,
  'settings': Icons.settings,
  'search': Icons.search,
  'plus': Icons.add,
  'edit': Icons.edit,
  'delete': Icons.delete,
  'check': Icons.check,
  'information': Icons.info,
  'lock': Icons.lock,
  'eye': Icons.visibility,
  'eyeOff': Icons.visibility_off,
  'bell': Icons.notifications,
  'calendar': Icons.calendar_today,
  'camera': Icons.camera_alt,
  'cart': Icons.shopping_cart,
  'cloud': Icons.cloud,
  'download': Icons.download,
  'upload': Icons.upload,
  'send': Icons.send,
  'save': Icons.save,
  'folder': Icons.folder,
  'file': Icons.insert_drive_file,
  'email': Icons.email,
  'phone': Icons.phone,
  'map': Icons.map,
  'bookmark': Icons.bookmark,
  'dashboard': Icons.dashboard,
  'wifi': Icons.wifi,
  'school': Icons.school,
  'work': Icons.work,
  'alarm': Icons.alarm,
  'apps': Icons.apps,
  'battery': Icons.battery_full,
  'build': Icons.build,
  'chat': Icons.chat,
  'cloudUpload': Icons.cloud_upload,
  'cloudDownload': Icons.cloud_download,
  'creditCard': Icons.credit_card,
  'currencyUsd': Icons.attach_money,
  'database': Icons.storage,
  'fileDocument': Icons.description,
  'flag': Icons.flag,
  'gift': Icons.card_giftcard,
  'heart': Icons.favorite,
  'key': Icons.key,
  'lightbulb': Icons.lightbulb,
  'link': Icons.link,
  'logout': Icons.logout,
  'music': Icons.music_note,
  'palette': Icons.palette,
  'printer': Icons.print,
  'shield': Icons.shield,
  'shopping': Icons.shopping_bag,
  'starOutline': Icons.star_border,
  'sync': Icons.sync,
  'thumbUp': Icons.thumb_up,
  'timeline': Icons.timeline,
  'trendingUp': Icons.trending_up,
  'update': Icons.update,
  'visibility': Icons.visibility,
  'volumeHigh': Icons.volume_up,
  'warning': Icons.warning,
  'zoomIn': Icons.zoom_in,
  'youtube': Icons.play_circle,
  'zodiacAquarius': Icons.water_drop,
  'zodiacAries': Icons.pets,
  'zodiacCancer': Icons.cruelty_free,
  'zodiacCapricorn': Icons.landscape,
  'zodiacGemini': Icons.people_alt,
  'zodiacLeo': Icons.wb_sunny,
  'zodiacLibra': Icons.balance,
  'zodiacPisces': Icons.set_meal,
  'zodiacSagittarius': Icons.explore,
  'zodiacScorpio': Icons.bug_report,
  'zodiacTaurus': Icons.agriculture,
  'zodiacVirgo': Icons.eco,
};
